# Generated by Django 5.0.6 on 2024-05-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='passw',
            field=models.CharField(default='', max_length=20),
        ),
    ]
