# Generated by Django 5.0.6 on 2024-05-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='phone',
        ),
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
