# Generated by Django 5.0.6 on 2024-06-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_cart_username_cart_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='phone',
        ),
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.CharField(default='guest', max_length=255),
        ),
    ]
